version: '3.2'

services:
 app:
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - ./app:/app
   command: >
     sh -c "python manage.py runserver 0.0.0.0:8000"
   environment:
    - DB_HOST=db
    - DB_NAME=paranuara
    - DB_USER=mongouser
    - DB_PASS=supersecretpassword
   depends_on:
    - db
 db:
   image: mongo:3.4-jessie
   restart: always
   volumes:
    - type: volume
      source: mongodb_data_volume
      target: /data/db
   ports:
    - "27018:27017"
   environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword
volumes:
  mongodb_data_volume:
    external: true